language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "SysTick"
  - git config user.email "zack.li@xbro.cn"
  - git add .
  - git commit -m "Update docs, Auto build by Travis."
  - git push --force --quiet "https://${FARAWAY_CI}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/SysTick/systick.github.io.git
