language: node_js
node_js: stable
before_install:
  - npm install -g hexo
install:
  - npm install
script:
  - hexo generate
after_script:
  - cd ./public
  - git init
  - git config user.name "zack.li"
  - git config user.email "zack.li@xbro.cn"
  - git add .
  - git commit -m "Update docss"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - hexo
env:
  global:
  - GH_REF: https://github.com/SysTick/systick.github.io.git
  - secure: GH_TKEN
